export const puzzleCompletionAbi = [
  {
    type: "function",
    name: "totalPoints",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [{ name: "points", type: "uint256" }],
  },
  {
    type: "function",
    name: "scoreFor",
    stateMutability: "pure",
    inputs: [
      { name: "rows", type: "uint16" },
      { name: "cols", type: "uint16" },
      { name: "moves", type: "uint32" },
      { name: "secondsTaken", type: "uint32" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getTopPlayers",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "players", type: "address[]" },
      { name: "points", type: "uint256[]" },
    ],
  },
  {
    type: "function",
    name: "getCompletion",
    stateMutability: "view",
    inputs: [
      { name: "puzzleHash", type: "bytes32" },
      { name: "player", type: "address" },
    ],
    outputs: [
      { name: "exists", type: "bool" },
      { name: "completedAt", type: "uint64" },
      { name: "rows", type: "uint16" },
      { name: "cols", type: "uint16" },
      { name: "moves", type: "uint32" },
      { name: "secondsTaken", type: "uint32" },
      { name: "score", type: "uint256" },
      { name: "completionHash", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "submitScore",
    stateMutability: "nonpayable",
    inputs: [
      { name: "puzzleHash", type: "bytes32" },
      { name: "rows", type: "uint16" },
      { name: "cols", type: "uint16" },
      { name: "moves", type: "uint32" },
      { name: "secondsTaken", type: "uint32" },
      { name: "completionHash", type: "bytes32" },
    ],
    outputs: [{ name: "improved", type: "bool" }],
  },
  {
    type: "event",
    name: "PuzzleCompleted",
    inputs: [
      { name: "puzzleHash", type: "bytes32", indexed: true },
      { name: "player", type: "address", indexed: true },
      { name: "rows", type: "uint16", indexed: false },
      { name: "cols", type: "uint16", indexed: false },
      { name: "moves", type: "uint32", indexed: false },
      { name: "secondsTaken", type: "uint32", indexed: false },
      { name: "score", type: "uint256", indexed: false },
      { name: "totalPoints", type: "uint256", indexed: false },
      { name: "completionHash", type: "bytes32", indexed: false },
      { name: "completedAt", type: "uint64", indexed: false },
      { name: "improved", type: "bool", indexed: false },
    ],
  },
] as const;
